### ISSUE TITLE
Flawed logic when adding to cache?

### ISSUE THREAD

**Issue by havlan** [lia54/LeCaR_old_repo#2]
https://github.com/lia54/LeCaR/blob/master/algorithms/LeCaR.py#L118
Are you really adding to both caches here? Or what's the point of this?
Trying to reproduce, and I find this part extremely confusing =)

**Comment by lia54** [comment]
Hi there, please find the link to the updated repo and source code for the LeCaR work below:
https://github.com/sylab/LeCaR
